version: "3.9"

# uffizzi integration
x-uffizzi:
  ingress:
    service: answer
    port: 5370

services:

  answer:
    image: "${ANSWER_IMAGE}"
    environment:
      - AUTO_INSTALL=true
      - DB_TYPE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=127.0.0.1:3306
      - DB_NAME=answer
      - LANGUAGE=en_US
      - SITE_NAME=answer-test
      - SITE_URL=http://localhost
      - CONTACT_EMAIL=test@answer.com
      - ADMIN_NAME=admin123
      - ADMIN_PASSWORD=admin123
      - ADMIN_EMAIL=admin123@admin.com
    volumes:
      - answer-data:/data
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 4000M

  mysql:
   image: mysql:latest
   environment:
    - MYSQL_DATABASE=answer
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
   healthcheck:
     test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-ppassword" ]
     timeout: 20s
     retries: 10
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']
   volumes:
      - sql_data:/var/lib/mysql
   deploy:
            resources:
              limits:
                memory: 500M

volumes:
  answer-data:
  sql_data:
